#=========================================================================
#============================ BombCrypto Bot =============================
#=========================================================================

#       oooooooooo.  ooooooooooooo  .oooooo..o   .oooo.     .oooo.   
#       `888'   `Y8b 8'   888   `8 d8P'    `Y8 .dP""Y88b  .dP""Y88b  
#        888     888      888      Y88bo.            ]8P'       ]8P' 
#        888oooo888'      888       `"Y8888o.      .d8P'      .d8P'  
#        888    `88b      888           `"Y88b   .dP'       .dP'     
#        888    .88P      888      oo     .d8P .oP     .o .oP     .o 
#       o888bood8P'      o888o     8""88888P'  8888888888 8888888888 
                                                      
#=========================================================================
#================ Please consider buying me a coffee :) ==================
#=========================================================================
#============== 0x7e665768270dF85A1D398498F9694C17e646Aa8C ===============
#================================= PIX ===================================
#================= 14c6beb5-a38a-46f1-b029-cf2e104712d0 ==================
#=========================================================================


#***************************BTS-KEY (OPTIONAL)***************************#
   ## ##   ### ##    ## ##     ####    ## ##   ###  ##    ##     ####     
  ##   ##   ##  ##  ##   ##     ##    ##   ##    ## ##     ##     ##      
  ##   ##   ##  ##  ##          ##    ##   ##   # ## #   ## ##    ##      
  ##   ##   ##  ##  ##          ##    ##   ##   ## ##    ##  ##   ##      
  ##   ##   ## ##   ##          ##    ##   ##   ##  ##   ## ###   ##      
  ##   ##   ##      ##   ##     ##    ##   ##   ##  ##   ##  ##   ##  ##  
   ## ##   ####      ## ##     ####    ## ##   ###  ##  ###  ##  ### ### 
    
  bts-key: "BTS-XXXXXXXXXXXXXXXXXXXX"

    #Get your BTS-Key here:
    # ---->   https://bit.ly/3ETbs90

    #SE PRECISAR, pegue sua BTS-Key aqui: 
    # ---->   https://bit.ly/3DXHqje
    
#-------------------------------------------------------------------------#

#************************TELEGRAM CONFIG (OPTIONAL)***********************#
#                                                 ..    
#                                            ..:::::    
#                                       ..::::..::::    
#                                 ...::::::. ..::::.    
#                            ...:::::::..  .:::::::     
#                        .:::::::::::    .::::::::.     
#                         ...::::..    :::::::::::      
#                                    .::::::::::::      
#                                   .:::::::::::::       
#                                  ::::::::::::::       
#                                  ::.   .:::::-.       
#                                  .        .:-:        

  # [en_US] Start a Telegram conversation with the @btsit_bot and type /id to get your_chat_id. 
  # [pt_BR] Inicie uma conversa no Telegram com @btsit_bot e digite /id para pegar o your_chat_id.

  # [en_US] Start a Telegram conversation with @botfather and type /newbot to get your_telegram_bot_token.  
  # [pt_BR] Inicie uma conversa no Telegram com @botfather e digite /newbot para pegar o your_telegram_bot_token.
  
  telegram:
    telegram_mode: false
    telegram_chat_id: ["YOUR_CHAT_ID", "YOUR_CHAT_ID2(optional)"]
    telegram_bot_key: "YOUR_TELEGRAM_BOT_TOKEN"
    enable_coin_report: false
    enable_map_report: false
    enable_emergency_call: false # [en_US] Enable to receive call on error/new captcha (in development) [pt_BR] Habilitar para receber chamada em caso de erro/novo captcha (em desenvolvimento)
    format_of_images: "jpg"

#-------------------------------------------------------------------------#

  # [en_US] Time intervals configuration
  #
  # [pt_BR] Configurações de intervalos de tempo
  #
  time_intervals:
    # [en_US] Time interval for check if there are available heroes to work
    # Default value (in minutes): [10,15] [min value, max value]
    #
    # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): [10,15] [valor minimo, valor maximo]
    send_heroes_for_work: [30,45]
    
    # [en_US] Time interval to update heroes position in the map
    # Default value (in minutes): [3,5] [min value, max value]
    #
    # [pt_BR] Intervalo de tempo para atualizar a posição dos heróis no mapa
    # Valor padrão (em minutos): [3,5] [valor minimo, valor maximo]
    refresh_heroes_positions: [3,4]

    # [en_US] Time interval between movements
    # Default value (in seconds): 1 
    #
    # [pt_BR] Intervalo de tempo entre movimentos
    # Valor padrão (em segundos): 1
    interval_between_movements: 1

  # [en_US] Value of chests
  #
  # [pt_BR] Valor de cada bau
  #
  value_chests:
    value_chest1: 0.01425
    value_chest2: 0.0325
    value_chest3: 0.1625
    value_chest4: 0.325

  # [en_US] Metamask configs
  #
  # [pt_BR] Configs da metamask
  #
  metamask:
    enable_login_metamask: false
    password: "METAMASK PASSWORD"

  # [en_US] How confident the bot needs to be to click the buttons (values from 0 to 1. 0 is the minimum value, 1 is the maximum value)
  #
  # [pt_BR] O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
  #
  threshold:
    # [en_US]
    # Default value: 0.7
    #
    # [pt_BR]
    # Valor padrão: 0.7
    default: 0.7

    # [en_US]
    # Default value: 0.5
    #
    # [pt_BR]
    # Valor padrão: 0.5
    error: 0.5

    # [en_US]
    # Default value: 0.8
    #
    # [pt_BR]
    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padrão: 0.9
    go_to_work_btn: 0.9

    # [en_US]
    # Default value: 0.8
    #
    # [pt_BR]
    # Valor padrão: 0.8
    green_bar: 0.8

    # [en_US]
    # Default value: 0.7
    #
    # [pt_BR]
    # Valor padrão: 0.7
    full_bar: 0.7

    # [en_US]
    # Default value: 0.5
    #
    # [pt_BR]
    # Valor padrão: 0.5
    chest: 0.5

  # [en_US] distance in pixels to click the work button
  #
  # [pt_BR] distancia em pixels para clickar no botão work
  #
  offsets:
    work_button: [120,140]           # [min value, max value]
    work_button_full: [90,110]       # [min value, max value]
    work_button_all: [10,50]         # [min value, max value]
    character_indicator: [100,200]   # [min value, max value]

  # [en_US]
  # Default value: 60
  #
  # [pt_BR]
  # Valor padrão: 60
  scroll_size: 60

  # [en_US]
  # Default value: 3
  #
  # [pt_BR]
  # Valor padrão: 3
  scroll_attempts: 3

  # [en_US]
  # Default value: true
  #
  # [pt_BR]
  # Valor padrão: true
  use_click_and_drag_instead_of_scroll: true

  # [en_US]
  # Default value: 200
  #
  # [pt_BR]
  # Valor padrão: 200
  click_and_drag_amount: 200

  # [en_US]
  # Default value: green
  # Available options:
  # all   = select all heroes (regardless of the stamina bar)
  # green = select the heroes with green stamina bar (half or full)
  # full  = select only the heroes with full stamina bar
  #
  # [pt_BR]
  # Valor padrão: green
  # Opções disponíveis:
  # all   = seleciona todos os heróis (independente da barra de stamina)
  # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
  # full  = seleciona somente os heróis com a barra de stamina cheia
  select_heroes_mode: "green"

  # [en_US] Option for save logs to a file (logs.txt)
  # Default value: False
  # Available options: False or True
  #
  # [pt_BR] Opção para salvar os logs em arquivo (logs.txt)
  # Valor padrão : False
  # Opções disponíveis: False ou True
  save_log_to_file: True  

  # [en_US] monitor that bot will use for play
  # Default value: 1
  #
  # [pt_BR] monitor que o bot usara para jogar
  # Valor padrão: 1
  monitor_to_use: 1

  # [en_US] show emojis in console
  # Default value: false
  #
  # [pt_BR] mostra emojis no console 
  # Valor padrão: false
  emoji: True

  # [en_US] show more information
  # Default value: false
  #
  # [pt_BR] mostra mais informações 
  # Valor padrão: false
  debug: False



















































  # [en_US] PLEASE DON'T CHANGE
  # [pt_BR] POR FAVOR NÃO ALTERE
  version: "1.1.1"